version: 2 # use CircleCI 2.0
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    working_directory: ~/work
    environment:
      GIT_REPO: git@github.com:TUS-OSK/oskt.us.git
    environment:
      GIT_NAME: CircleCI
    environment:
      GIT_EMAIL: pnlybubbles+circleci@gmail.com
    docker:
      - image: node:7.6.0
    steps:
      - checkout
      - run:
          name: setup-environment-valuable
          command: echo 'export PATH="./node_modules/bin:$PATH"' >> ~/.bashrc
      - run:
          name: reload-bashrc
          command: source ~/.bashrc
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: run-build-script
          command: bash -x ./task/ci.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
