version: 2 # use CircleCI 2.0

jobs:
  npm_test:
    working_directory: ~/work
    docker:
      - image: node:7.6.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: install-npm-wee
          command: npm install
      - run:
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  workflows:
    version: 2
    test-and-build:
      jobs:
        - npm_test
